apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reviewers-contest-sso.fullname" . }}
  labels:
    {{- include "reviewers-contest-sso.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "reviewers-contest-sso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reviewers-contest-sso.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "reviewers-contest-sso.fullname" . }}
                  key: client_secret
            - name: CLINET_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "reviewers-contest-sso.fullname" . }}
                  key: client_id
          ports:
            - name: rest
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: rest
          readinessProbe:
            httpGet:
              path: /
              port: rest
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
