apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reviewers-contest-sso.fullname" . }}
  labels:
    {{- include "reviewers-contest-sso.labels" . | nindent 4 }}
type: Opaque
data:
  client_secret: {{ .Values.client_secret | quote }}
  client_id: {{ .Values.client_id | quote }}