apiVersion: v1
kind: Service
metadata:
  name: {{ include "reviewers-contest-sso.fullname" . }}
  labels:
    {{- include "reviewers-contest-sso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8090
      protocol: TCP
      name: rest
  selector:
    {{- include "reviewers-contest-sso.selectorLabels" . | nindent 4 }}
